





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using Glass.Mapper.Sc.Demo.Core.Fields;


namespace Glass.Mapper.Sc.Demo.Core.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }
	}
}
namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// ILanding Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Landing</para>	
	/// <para>ID: 020c8626-b8ba-4351-92eb-d1ff45800a59</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILandingConstants.TemplateIdString, Cachable = true )]
	public partial interface ILanding : IGlassBase , global::Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Base.IPageBase, global::Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Interface.IFeature
	{
								/// <summary>
					/// The LandingContent field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 8fb79ba2-269f-4266-b06e-463a7886abb6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ILandingConstants.LandingContentFieldName)]
					string LandingContent  {get; set;}
			
				}


	public static partial class ILandingConstants{

			public const string TemplateIdString = "020c8626-b8ba-4351-92eb-d1ff45800a59";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Landing";

					
			public static readonly ID LandingContentFieldId = new ID("8fb79ba2-269f-4266-b06e-463a7886abb6");
			public const string LandingContentFieldName = "LandingContent";
			
					
			public static readonly ID IPageTitlesLongTitleFieldId = new ID("73f291bc-4098-4702-b0da-8b0416751e81");
			public const string IPageTitlesLongTitleFieldName = "IPageTitlesLongTitle";
			
					
			public static readonly ID IPageTitlesShortTitleFieldId = new ID("04e95463-a928-4cc0-b855-fb9f341c2221");
			public const string IPageTitlesShortTitleFieldName = "IPageTitlesShortTitle";
			
					
			public static readonly ID IPageTitleSubTitleFieldId = new ID("adf2c63c-d097-4aec-b86f-571d772e441a");
			public const string IPageTitleSubTitleFieldName = "IPageTitleSubTitle";
			
					
			public static readonly ID IFeatureAbstractFieldId = new ID("e279fb5a-76a4-4519-92b1-c6215717042a");
			public const string IFeatureAbstractFieldName = "IFeatureAbstract";
			
					
			public static readonly ID IFeatureFeaturedFieldId = new ID("6dab1a4b-166a-4ffe-b1c6-30f80f56b013");
			public const string IFeatureFeaturedFieldName = "IFeatureFeatured";
			
					
			public static readonly ID IFeatureImageFieldId = new ID("bca36a19-5bbd-4f18-8f7c-3d936018ba0e");
			public const string IFeatureImageFieldName = "IFeatureImage";
			
			

	}

	
	/// <summary>
	/// Landing
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Landing</para>	
	/// <para>ID: 020c8626-b8ba-4351-92eb-d1ff45800a59</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILandingConstants.TemplateIdString, Cachable = true)]
	public partial class Landing  : GlassBase, ILanding 
	{
	   
						/// <summary>
				/// The LandingContent field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 8fb79ba2-269f-4266-b06e-463a7886abb6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.LandingContentFieldName)]
				public virtual string LandingContent  {get; set;}
					
						/// <summary>
				/// The IPageTitlesLongTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 73f291bc-4098-4702-b0da-8b0416751e81</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IPageTitlesLongTitleFieldName)]
				public virtual string IPageTitlesLongTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShortTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 04e95463-a928-4cc0-b855-fb9f341c2221</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IPageTitlesShortTitleFieldName)]
				public virtual string IPageTitlesShortTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitleSubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: adf2c63c-d097-4aec-b86f-571d772e441a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IPageTitleSubTitleFieldName)]
				public virtual string IPageTitleSubTitle  {get; set;}
					
						/// <summary>
				/// The IFeatureAbstract field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: e279fb5a-76a4-4519-92b1-c6215717042a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IFeatureAbstractFieldName)]
				public virtual string IFeatureAbstract  {get; set;}
					
						/// <summary>
				/// The IFeatureFeatured field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 6dab1a4b-166a-4ffe-b1c6-30f80f56b013</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IFeatureFeaturedFieldName)]
				public virtual bool IFeatureFeatured  {get; set;}
					
						/// <summary>
				/// The IFeatureImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: bca36a19-5bbd-4f18-8f7c-3d936018ba0e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILandingConstants.IFeatureImageFieldName)]
				public virtual ExifImage IFeatureImage  {get; set;}
					
			
	}
}




namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IComment Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Comment</para>	
	/// <para>ID: 05ab9c1a-8308-43d4-8e68-8df503a06dc9</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentConstants.TemplateIdString, Cachable = true )]
	public partial interface IComment : IGlassBase 
	{
								/// <summary>
					/// The CommentEmail field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b96e2942-b55f-4aef-bb5b-dcac931f97cc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.CommentEmailFieldName)]
					string CommentEmail  {get; set;}
			
								/// <summary>
					/// The CommentItem field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: 991d867a-877f-4058-b513-52b28bd8e67f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.CommentItemFieldName)]
					Guid CommentItem  {get; set;}
			
								/// <summary>
					/// The CommentMessage field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: fa028db7-c6a7-4ae6-88d9-4adccb188b2b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.CommentMessageFieldName)]
					string CommentMessage  {get; set;}
			
								/// <summary>
					/// The CommentName field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 853c86ad-1e3f-431d-b6c5-a84bc8708154</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.CommentNameFieldName)]
					string CommentName  {get; set;}
			
				}


	public static partial class ICommentConstants{

			public const string TemplateIdString = "05ab9c1a-8308-43d4-8e68-8df503a06dc9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Comment";

					
			public static readonly ID CommentEmailFieldId = new ID("b96e2942-b55f-4aef-bb5b-dcac931f97cc");
			public const string CommentEmailFieldName = "CommentEmail";
			
					
			public static readonly ID CommentItemFieldId = new ID("991d867a-877f-4058-b513-52b28bd8e67f");
			public const string CommentItemFieldName = "CommentItem";
			
					
			public static readonly ID CommentMessageFieldId = new ID("fa028db7-c6a7-4ae6-88d9-4adccb188b2b");
			public const string CommentMessageFieldName = "CommentMessage";
			
					
			public static readonly ID CommentNameFieldId = new ID("853c86ad-1e3f-431d-b6c5-a84bc8708154");
			public const string CommentNameFieldName = "CommentName";
			
			

	}

	
	/// <summary>
	/// Comment
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Comment</para>	
	/// <para>ID: 05ab9c1a-8308-43d4-8e68-8df503a06dc9</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentConstants.TemplateIdString, Cachable = true)]
	public partial class Comment  : GlassBase, IComment 
	{
	   
						/// <summary>
				/// The CommentEmail field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b96e2942-b55f-4aef-bb5b-dcac931f97cc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.CommentEmailFieldName)]
				public virtual string CommentEmail  {get; set;}
					
						/// <summary>
				/// The CommentItem field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: 991d867a-877f-4058-b513-52b28bd8e67f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.CommentItemFieldName)]
				public virtual Guid CommentItem  {get; set;}
					
						/// <summary>
				/// The CommentMessage field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: fa028db7-c6a7-4ae6-88d9-4adccb188b2b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.CommentMessageFieldName)]
				public virtual string CommentMessage  {get; set;}
					
						/// <summary>
				/// The CommentName field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 853c86ad-1e3f-431d-b6c5-a84bc8708154</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.CommentNameFieldName)]
				public virtual string CommentName  {get; set;}
					
			
	}
}


























namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Base
{


 	/// <summary>
	/// IPageBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Base/PageBase</para>	
	/// <para>ID: 326ae029-dfd8-41a6-a1e9-ce4de66a7d2b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString, Cachable = true )]
	public partial interface IPageBase : IGlassBase , global::Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Common.Interface.IPageTitles
	{
				}


	public static partial class IPageBaseConstants{

			public const string TemplateIdString = "326ae029-dfd8-41a6-a1e9-ce4de66a7d2b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "PageBase";

					
			public static readonly ID IPageTitlesLongTitleFieldId = new ID("73f291bc-4098-4702-b0da-8b0416751e81");
			public const string IPageTitlesLongTitleFieldName = "IPageTitlesLongTitle";
			
					
			public static readonly ID IPageTitlesShortTitleFieldId = new ID("04e95463-a928-4cc0-b855-fb9f341c2221");
			public const string IPageTitlesShortTitleFieldName = "IPageTitlesShortTitle";
			
					
			public static readonly ID IPageTitleSubTitleFieldId = new ID("adf2c63c-d097-4aec-b86f-571d772e441a");
			public const string IPageTitleSubTitleFieldName = "IPageTitleSubTitle";
			
			

	}

	
	/// <summary>
	/// PageBase
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Base/PageBase</para>	
	/// <para>ID: 326ae029-dfd8-41a6-a1e9-ce4de66a7d2b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageBaseConstants.TemplateIdString, Cachable = true)]
	public partial class PageBase  : GlassBase, IPageBase 
	{
	   
						/// <summary>
				/// The IPageTitlesLongTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 73f291bc-4098-4702-b0da-8b0416751e81</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.IPageTitlesLongTitleFieldName)]
				public virtual string IPageTitlesLongTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShortTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 04e95463-a928-4cc0-b855-fb9f341c2221</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.IPageTitlesShortTitleFieldName)]
				public virtual string IPageTitlesShortTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitleSubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: adf2c63c-d097-4aec-b86f-571d772e441a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageBaseConstants.IPageTitleSubTitleFieldName)]
				public virtual string IPageTitleSubTitle  {get; set;}
					
			
	}
}

namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Common.Static
{


 	/// <summary>
	/// IComments Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Static/Comments</para>	
	/// <para>ID: 3b990644-58b6-4d51-b872-9effc52253f2</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentsConstants.TemplateIdString, Cachable = true )]
	public partial interface IComments : IGlassBase 
	{
								/// <summary>
					/// The Thanks field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 64b1d75c-8eef-4b51-b84f-b1bfc309031e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentsConstants.ThanksFieldName)]
					string Thanks  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ab9553ca-0a2e-462e-a77d-7b5d6818829d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentsConstants.TitleFieldName)]
					string Title  {get; set;}
			
								/// <summary>
					/// The YourComment field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d7d3f9b2-ac04-47ed-b2de-97a1f54cffa4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentsConstants.YourCommentFieldName)]
					string YourComment  {get; set;}
			
				}


	public static partial class ICommentsConstants{

			public const string TemplateIdString = "3b990644-58b6-4d51-b872-9effc52253f2";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Comments";

					
			public static readonly ID ThanksFieldId = new ID("64b1d75c-8eef-4b51-b84f-b1bfc309031e");
			public const string ThanksFieldName = "Thanks";
			
					
			public static readonly ID TitleFieldId = new ID("ab9553ca-0a2e-462e-a77d-7b5d6818829d");
			public const string TitleFieldName = "Title";
			
					
			public static readonly ID YourCommentFieldId = new ID("d7d3f9b2-ac04-47ed-b2de-97a1f54cffa4");
			public const string YourCommentFieldName = "YourComment";
			
			

	}

	
	/// <summary>
	/// Comments
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Static/Comments</para>	
	/// <para>ID: 3b990644-58b6-4d51-b872-9effc52253f2</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentsConstants.TemplateIdString, Cachable = true)]
	public partial class Comments  : GlassBase, IComments 
	{
	   
						/// <summary>
				/// The Thanks field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 64b1d75c-8eef-4b51-b84f-b1bfc309031e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentsConstants.ThanksFieldName)]
				public virtual string Thanks  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ab9553ca-0a2e-462e-a77d-7b5d6818829d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentsConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
						/// <summary>
				/// The YourComment field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d7d3f9b2-ac04-47ed-b2de-97a1f54cffa4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentsConstants.YourCommentFieldName)]
				public virtual string YourComment  {get; set;}
					
			
	}
}






namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IRateBacon Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/RateBacon</para>	
	/// <para>ID: 44da61dc-9ac8-400e-9555-53e920f9a5d9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRateBaconConstants.TemplateIdString, Cachable = true )]
	public partial interface IRateBacon : IGlassBase 
	{
								/// <summary>
					/// The RateBaconCount1 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: e1d724b9-4e6d-4998-ac84-29d29d0cbad3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconCount1FieldName)]
					float RateBaconCount1  {get; set;}
			
								/// <summary>
					/// The RateBaconCount2 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: eaa38e7b-741b-4eee-b8d4-1f1d5c0eafcc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconCount2FieldName)]
					float RateBaconCount2  {get; set;}
			
								/// <summary>
					/// The RateBaconCount3 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: a56f4168-a227-42c2-a6a1-d118647f8528</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconCount3FieldName)]
					float RateBaconCount3  {get; set;}
			
								/// <summary>
					/// The RateBaconCount4 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: fd23f899-8138-44f7-9b44-d5d5ffcab633</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconCount4FieldName)]
					float RateBaconCount4  {get; set;}
			
								/// <summary>
					/// The RateBaconImage1 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 5a87cc65-4510-4ff8-a358-ebdc284f7d1c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconImage1FieldName)]
					ExifImage RateBaconImage1  {get; set;}
			
								/// <summary>
					/// The RateBaconImage2 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 79d2f3f9-a7a3-40cb-9e0d-0b1251e2902e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconImage2FieldName)]
					ExifImage RateBaconImage2  {get; set;}
			
								/// <summary>
					/// The RateBaconImage3 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: ab61dee9-6fcd-46fd-8b86-776556543da0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconImage3FieldName)]
					ExifImage RateBaconImage3  {get; set;}
			
								/// <summary>
					/// The RateBaconImage4 field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: fe260f87-e7ac-49fc-a719-aae2ec5bb05a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconImage4FieldName)]
					ExifImage RateBaconImage4  {get; set;}
			
								/// <summary>
					/// The RateBaconRate1 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 4652c5ed-1dd0-4bd6-a8f5-44f0e96bb362</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconRate1FieldName)]
					float RateBaconRate1  {get; set;}
			
								/// <summary>
					/// The RateBaconRate2 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 6b47eb72-7e85-45a2-8b3b-54f6d4c53de0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconRate2FieldName)]
					float RateBaconRate2  {get; set;}
			
								/// <summary>
					/// The RateBaconRate3 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 50d7deee-f99a-4c6c-bafb-a534f724a90a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconRate3FieldName)]
					float RateBaconRate3  {get; set;}
			
								/// <summary>
					/// The RateBaconRate4 field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 1e6d4592-a5fa-4373-beaf-5a5d9bf76241</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRateBaconConstants.RateBaconRate4FieldName)]
					float RateBaconRate4  {get; set;}
			
				}


	public static partial class IRateBaconConstants{

			public const string TemplateIdString = "44da61dc-9ac8-400e-9555-53e920f9a5d9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RateBacon";

					
			public static readonly ID RateBaconCount1FieldId = new ID("e1d724b9-4e6d-4998-ac84-29d29d0cbad3");
			public const string RateBaconCount1FieldName = "RateBaconCount1";
			
					
			public static readonly ID RateBaconCount2FieldId = new ID("eaa38e7b-741b-4eee-b8d4-1f1d5c0eafcc");
			public const string RateBaconCount2FieldName = "RateBaconCount2";
			
					
			public static readonly ID RateBaconCount3FieldId = new ID("a56f4168-a227-42c2-a6a1-d118647f8528");
			public const string RateBaconCount3FieldName = "RateBaconCount3";
			
					
			public static readonly ID RateBaconCount4FieldId = new ID("fd23f899-8138-44f7-9b44-d5d5ffcab633");
			public const string RateBaconCount4FieldName = "RateBaconCount4";
			
					
			public static readonly ID RateBaconImage1FieldId = new ID("5a87cc65-4510-4ff8-a358-ebdc284f7d1c");
			public const string RateBaconImage1FieldName = "RateBaconImage1";
			
					
			public static readonly ID RateBaconImage2FieldId = new ID("79d2f3f9-a7a3-40cb-9e0d-0b1251e2902e");
			public const string RateBaconImage2FieldName = "RateBaconImage2";
			
					
			public static readonly ID RateBaconImage3FieldId = new ID("ab61dee9-6fcd-46fd-8b86-776556543da0");
			public const string RateBaconImage3FieldName = "RateBaconImage3";
			
					
			public static readonly ID RateBaconImage4FieldId = new ID("fe260f87-e7ac-49fc-a719-aae2ec5bb05a");
			public const string RateBaconImage4FieldName = "RateBaconImage4";
			
					
			public static readonly ID RateBaconRate1FieldId = new ID("4652c5ed-1dd0-4bd6-a8f5-44f0e96bb362");
			public const string RateBaconRate1FieldName = "RateBaconRate1";
			
					
			public static readonly ID RateBaconRate2FieldId = new ID("6b47eb72-7e85-45a2-8b3b-54f6d4c53de0");
			public const string RateBaconRate2FieldName = "RateBaconRate2";
			
					
			public static readonly ID RateBaconRate3FieldId = new ID("50d7deee-f99a-4c6c-bafb-a534f724a90a");
			public const string RateBaconRate3FieldName = "RateBaconRate3";
			
					
			public static readonly ID RateBaconRate4FieldId = new ID("1e6d4592-a5fa-4373-beaf-5a5d9bf76241");
			public const string RateBaconRate4FieldName = "RateBaconRate4";
			
			

	}

	
	/// <summary>
	/// RateBacon
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/RateBacon</para>	
	/// <para>ID: 44da61dc-9ac8-400e-9555-53e920f9a5d9</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRateBaconConstants.TemplateIdString, Cachable = true)]
	public partial class RateBacon  : GlassBase, IRateBacon 
	{
	   
						/// <summary>
				/// The RateBaconCount1 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: e1d724b9-4e6d-4998-ac84-29d29d0cbad3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconCount1FieldName)]
				public virtual float RateBaconCount1  {get; set;}
					
						/// <summary>
				/// The RateBaconCount2 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: eaa38e7b-741b-4eee-b8d4-1f1d5c0eafcc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconCount2FieldName)]
				public virtual float RateBaconCount2  {get; set;}
					
						/// <summary>
				/// The RateBaconCount3 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: a56f4168-a227-42c2-a6a1-d118647f8528</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconCount3FieldName)]
				public virtual float RateBaconCount3  {get; set;}
					
						/// <summary>
				/// The RateBaconCount4 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: fd23f899-8138-44f7-9b44-d5d5ffcab633</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconCount4FieldName)]
				public virtual float RateBaconCount4  {get; set;}
					
						/// <summary>
				/// The RateBaconImage1 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 5a87cc65-4510-4ff8-a358-ebdc284f7d1c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconImage1FieldName)]
				public virtual ExifImage RateBaconImage1  {get; set;}
					
						/// <summary>
				/// The RateBaconImage2 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 79d2f3f9-a7a3-40cb-9e0d-0b1251e2902e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconImage2FieldName)]
				public virtual ExifImage RateBaconImage2  {get; set;}
					
						/// <summary>
				/// The RateBaconImage3 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: ab61dee9-6fcd-46fd-8b86-776556543da0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconImage3FieldName)]
				public virtual ExifImage RateBaconImage3  {get; set;}
					
						/// <summary>
				/// The RateBaconImage4 field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: fe260f87-e7ac-49fc-a719-aae2ec5bb05a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconImage4FieldName)]
				public virtual ExifImage RateBaconImage4  {get; set;}
					
						/// <summary>
				/// The RateBaconRate1 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 4652c5ed-1dd0-4bd6-a8f5-44f0e96bb362</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconRate1FieldName)]
				public virtual float RateBaconRate1  {get; set;}
					
						/// <summary>
				/// The RateBaconRate2 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 6b47eb72-7e85-45a2-8b3b-54f6d4c53de0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconRate2FieldName)]
				public virtual float RateBaconRate2  {get; set;}
					
						/// <summary>
				/// The RateBaconRate3 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 50d7deee-f99a-4c6c-bafb-a534f724a90a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconRate3FieldName)]
				public virtual float RateBaconRate3  {get; set;}
					
						/// <summary>
				/// The RateBaconRate4 field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 1e6d4592-a5fa-4373-beaf-5a5d9bf76241</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRateBaconConstants.RateBaconRate4FieldName)]
				public virtual float RateBaconRate4  {get; set;}
					
			
	}
}














namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Misc
{


 	/// <summary>
	/// ILookup Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Misc/Lookup</para>	
	/// <para>ID: 58846d10-58d9-40b4-a31f-0f70b2c128a9</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILookupConstants.TemplateIdString, Cachable = true )]
	public partial interface ILookup : IGlassBase 
	{
				}


	public static partial class ILookupConstants{

			public const string TemplateIdString = "58846d10-58d9-40b4-a31f-0f70b2c128a9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Lookup";

			

	}

	
	/// <summary>
	/// Lookup
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Misc/Lookup</para>	
	/// <para>ID: 58846d10-58d9-40b4-a31f-0f70b2c128a9</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILookupConstants.TemplateIdString, Cachable = true)]
	public partial class Lookup  : GlassBase, ILookup 
	{
	   
			
	}
}














namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IQuickLink Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/QuickLink</para>	
	/// <para>ID: 6ba9eb58-2267-4fde-8bb0-8e55670d61f0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IQuickLinkConstants.TemplateIdString, Cachable = true )]
	public partial interface IQuickLink : IGlassBase 
	{
								/// <summary>
					/// The Icon field.
					/// <para></para>
					/// <para>Field Type: Droplist</para>		
					/// <para>Field ID: 23ab0434-7586-4333-b5a9-3a1ac6fb2cc3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IQuickLinkConstants.IconFieldName)]
					string Icon  {get; set;}
			
								/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 63cd2c33-a35d-4375-bbe6-804104d58110</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IQuickLinkConstants.LinkFieldName)]
					Link Link  {get; set;}
			
				}


	public static partial class IQuickLinkConstants{

			public const string TemplateIdString = "6ba9eb58-2267-4fde-8bb0-8e55670d61f0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "QuickLink";

					
			public static readonly ID IconFieldId = new ID("23ab0434-7586-4333-b5a9-3a1ac6fb2cc3");
			public const string IconFieldName = "Icon";
			
					
			public static readonly ID LinkFieldId = new ID("63cd2c33-a35d-4375-bbe6-804104d58110");
			public const string LinkFieldName = "Link";
			
			

	}

	
	/// <summary>
	/// QuickLink
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/QuickLink</para>	
	/// <para>ID: 6ba9eb58-2267-4fde-8bb0-8e55670d61f0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IQuickLinkConstants.TemplateIdString, Cachable = true)]
	public partial class QuickLink  : GlassBase, IQuickLink 
	{
	   
						/// <summary>
				/// The Icon field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: 23ab0434-7586-4333-b5a9-3a1ac6fb2cc3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IQuickLinkConstants.IconFieldName)]
				public virtual string Icon  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 63cd2c33-a35d-4375-bbe6-804104d58110</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IQuickLinkConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
			
	}
}





















namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Common.Interface
{


 	/// <summary>
	/// IPageTitles Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Interface/IPageTitles</para>	
	/// <para>ID: 92b1c7ab-4309-4dd7-8e0e-59e0ec22ff80</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageTitlesConstants.TemplateIdString, Cachable = true )]
	public partial interface IPageTitles : IGlassBase 
	{
								/// <summary>
					/// The IPageTitlesLongTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 73f291bc-4098-4702-b0da-8b0416751e81</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageTitlesConstants.IPageTitlesLongTitleFieldName)]
					string IPageTitlesLongTitle  {get; set;}
			
								/// <summary>
					/// The IPageTitlesShortTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 04e95463-a928-4cc0-b855-fb9f341c2221</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageTitlesConstants.IPageTitlesShortTitleFieldName)]
					string IPageTitlesShortTitle  {get; set;}
			
								/// <summary>
					/// The IPageTitleSubTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: adf2c63c-d097-4aec-b86f-571d772e441a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageTitlesConstants.IPageTitleSubTitleFieldName)]
					string IPageTitleSubTitle  {get; set;}
			
				}


	public static partial class IPageTitlesConstants{

			public const string TemplateIdString = "92b1c7ab-4309-4dd7-8e0e-59e0ec22ff80";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "IPageTitles";

					
			public static readonly ID IPageTitlesLongTitleFieldId = new ID("73f291bc-4098-4702-b0da-8b0416751e81");
			public const string IPageTitlesLongTitleFieldName = "IPageTitlesLongTitle";
			
					
			public static readonly ID IPageTitlesShortTitleFieldId = new ID("04e95463-a928-4cc0-b855-fb9f341c2221");
			public const string IPageTitlesShortTitleFieldName = "IPageTitlesShortTitle";
			
					
			public static readonly ID IPageTitleSubTitleFieldId = new ID("adf2c63c-d097-4aec-b86f-571d772e441a");
			public const string IPageTitleSubTitleFieldName = "IPageTitleSubTitle";
			
			

	}

}
namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IHomePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/HomePage</para>	
	/// <para>ID: 9303fd9f-90fb-4795-9121-219a014591cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomePageConstants.TemplateIdString, Cachable = true )]
	public partial interface IHomePage : IGlassBase , global::Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Base.IPageBase
	{
								/// <summary>
					/// The DeveloperImage field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: f4cb2be2-e502-4059-9d10-b76562be8e8f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomePageConstants.DeveloperImageFieldName)]
					ExifImage DeveloperImage  {get; set;}
			
								/// <summary>
					/// The DeveloperLink field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 0f0ab893-371d-4a44-8cb6-d7b67f9de6c1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomePageConstants.DeveloperLinkFieldName)]
					Link DeveloperLink  {get; set;}
			
								/// <summary>
					/// The DeveloperName field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 0e88778c-6275-409e-86d8-9f105942c871</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomePageConstants.DeveloperNameFieldName)]
					string DeveloperName  {get; set;}
			
								/// <summary>
					/// The HomeFeatured field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: 1fe7ff64-4c8b-49e0-8eef-6470234ded6b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomePageConstants.HomeFeaturedsFieldName)]
					IEnumerable<Guid> HomeFeatureds  {get; set;}
			
								/// <summary>
					/// The HomeSearch field.
					/// <para></para>
					/// <para>Field Type: Droptree</para>		
					/// <para>Field ID: c23ab561-0c56-41a2-8ff7-9db9d9991abd</para>
					/// <para>Custom Data: type=Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete.Search</para>
					/// </summary>
					[SitecoreField(IHomePageConstants.HomeSearchFieldName)]
					Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete.Search HomeSearch  {get; set;}
			
								/// <summary>
					/// The HomeSiteLogo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: c480cbfc-74d6-49f5-a894-43f53d122032</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomePageConstants.HomeSiteLogoFieldName)]
					ExifImage HomeSiteLogo  {get; set;}
			
								/// <summary>
					/// The HomeSiteName field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 6d944193-da45-405c-91be-74f9a57e7cc9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomePageConstants.HomeSiteNameFieldName)]
					string HomeSiteName  {get; set;}
			
				}


	public static partial class IHomePageConstants{

			public const string TemplateIdString = "9303fd9f-90fb-4795-9121-219a014591cd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomePage";

					
			public static readonly ID DeveloperImageFieldId = new ID("f4cb2be2-e502-4059-9d10-b76562be8e8f");
			public const string DeveloperImageFieldName = "DeveloperImage";
			
					
			public static readonly ID DeveloperLinkFieldId = new ID("0f0ab893-371d-4a44-8cb6-d7b67f9de6c1");
			public const string DeveloperLinkFieldName = "DeveloperLink";
			
					
			public static readonly ID DeveloperNameFieldId = new ID("0e88778c-6275-409e-86d8-9f105942c871");
			public const string DeveloperNameFieldName = "DeveloperName";
			
					
			public static readonly ID HomeFeaturedsFieldId = new ID("1fe7ff64-4c8b-49e0-8eef-6470234ded6b");
			public const string HomeFeaturedsFieldName = "HomeFeatured";
			
					
			public static readonly ID HomeSearchFieldId = new ID("c23ab561-0c56-41a2-8ff7-9db9d9991abd");
			public const string HomeSearchFieldName = "HomeSearch";
			
					
			public static readonly ID HomeSiteLogoFieldId = new ID("c480cbfc-74d6-49f5-a894-43f53d122032");
			public const string HomeSiteLogoFieldName = "HomeSiteLogo";
			
					
			public static readonly ID HomeSiteNameFieldId = new ID("6d944193-da45-405c-91be-74f9a57e7cc9");
			public const string HomeSiteNameFieldName = "HomeSiteName";
			
					
			public static readonly ID IPageTitlesLongTitleFieldId = new ID("73f291bc-4098-4702-b0da-8b0416751e81");
			public const string IPageTitlesLongTitleFieldName = "IPageTitlesLongTitle";
			
					
			public static readonly ID IPageTitlesShortTitleFieldId = new ID("04e95463-a928-4cc0-b855-fb9f341c2221");
			public const string IPageTitlesShortTitleFieldName = "IPageTitlesShortTitle";
			
					
			public static readonly ID IPageTitleSubTitleFieldId = new ID("adf2c63c-d097-4aec-b86f-571d772e441a");
			public const string IPageTitleSubTitleFieldName = "IPageTitleSubTitle";
			
			

	}

	
	/// <summary>
	/// HomePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/HomePage</para>	
	/// <para>ID: 9303fd9f-90fb-4795-9121-219a014591cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomePageConstants.TemplateIdString, Cachable = true)]
	public partial class HomePage  : GlassBase, IHomePage 
	{
	   
						/// <summary>
				/// The DeveloperImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: f4cb2be2-e502-4059-9d10-b76562be8e8f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.DeveloperImageFieldName)]
				public virtual ExifImage DeveloperImage  {get; set;}
					
						/// <summary>
				/// The DeveloperLink field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 0f0ab893-371d-4a44-8cb6-d7b67f9de6c1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.DeveloperLinkFieldName)]
				public virtual Link DeveloperLink  {get; set;}
					
						/// <summary>
				/// The DeveloperName field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 0e88778c-6275-409e-86d8-9f105942c871</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.DeveloperNameFieldName)]
				public virtual string DeveloperName  {get; set;}
					
						/// <summary>
				/// The HomeFeatured field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 1fe7ff64-4c8b-49e0-8eef-6470234ded6b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.HomeFeaturedsFieldName)]
				public virtual IEnumerable<Guid> HomeFeatureds  {get; set;}
					
						/// <summary>
				/// The HomeSearch field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// <para>Field ID: c23ab561-0c56-41a2-8ff7-9db9d9991abd</para>
				/// <para>Custom Data: type=Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete.Search</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.HomeSearchFieldName)]
				public virtual Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete.Search HomeSearch  {get; set;}
					
						/// <summary>
				/// The HomeSiteLogo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: c480cbfc-74d6-49f5-a894-43f53d122032</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.HomeSiteLogoFieldName)]
				public virtual ExifImage HomeSiteLogo  {get; set;}
					
						/// <summary>
				/// The HomeSiteName field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 6d944193-da45-405c-91be-74f9a57e7cc9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.HomeSiteNameFieldName)]
				public virtual string HomeSiteName  {get; set;}
					
						/// <summary>
				/// The IPageTitlesLongTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 73f291bc-4098-4702-b0da-8b0416751e81</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.IPageTitlesLongTitleFieldName)]
				public virtual string IPageTitlesLongTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShortTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 04e95463-a928-4cc0-b855-fb9f341c2221</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.IPageTitlesShortTitleFieldName)]
				public virtual string IPageTitlesShortTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitleSubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: adf2c63c-d097-4aec-b86f-571d772e441a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.IPageTitleSubTitleFieldName)]
				public virtual string IPageTitleSubTitle  {get; set;}
					
			
	}
}












namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Common
{


 	/// <summary>
	/// IFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Folder</para>	
	/// <para>ID: a87a00b1-e6db-45ab-8b54-636fec3b5523</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFolderConstants.TemplateIdString, Cachable = true )]
	public partial interface IFolder : IGlassBase 
	{
				}


	public static partial class IFolderConstants{

			public const string TemplateIdString = "a87a00b1-e6db-45ab-8b54-636fec3b5523";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Folder";

			

	}

	
	/// <summary>
	/// Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Common/Folder</para>	
	/// <para>ID: a87a00b1-e6db-45ab-8b54-636fec3b5523</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFolderConstants.TemplateIdString, Cachable = true)]
	public partial class Folder  : GlassBase, IFolder 
	{
	   
			
	}
}

























namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Interface
{


 	/// <summary>
	/// IFeature Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Interface/IFeature</para>	
	/// <para>ID: ccd32cba-0045-46c7-a3ac-24624864de36</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFeatureConstants.TemplateIdString, Cachable = true )]
	public partial interface IFeature : IGlassBase 
	{
								/// <summary>
					/// The IFeatureAbstract field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: e279fb5a-76a4-4519-92b1-c6215717042a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureConstants.IFeatureAbstractFieldName)]
					string IFeatureAbstract  {get; set;}
			
								/// <summary>
					/// The IFeatureFeatured field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 6dab1a4b-166a-4ffe-b1c6-30f80f56b013</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureConstants.IFeatureFeaturedFieldName)]
					bool IFeatureFeatured  {get; set;}
			
								/// <summary>
					/// The IFeatureImage field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: bca36a19-5bbd-4f18-8f7c-3d936018ba0e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFeatureConstants.IFeatureImageFieldName)]
					ExifImage IFeatureImage  {get; set;}
			
				}


	public static partial class IFeatureConstants{

			public const string TemplateIdString = "ccd32cba-0045-46c7-a3ac-24624864de36";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "IFeature";

					
			public static readonly ID IFeatureAbstractFieldId = new ID("e279fb5a-76a4-4519-92b1-c6215717042a");
			public const string IFeatureAbstractFieldName = "IFeatureAbstract";
			
					
			public static readonly ID IFeatureFeaturedFieldId = new ID("6dab1a4b-166a-4ffe-b1c6-30f80f56b013");
			public const string IFeatureFeaturedFieldName = "IFeatureFeatured";
			
					
			public static readonly ID IFeatureImageFieldId = new ID("bca36a19-5bbd-4f18-8f7c-3d936018ba0e");
			public const string IFeatureImageFieldName = "IFeatureImage";
			
			

	}

}










namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// IHtmlEmbed Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/HtmlEmbed</para>	
	/// <para>ID: e444df7d-4d75-4e48-857f-224d19766b4b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHtmlEmbedConstants.TemplateIdString, Cachable = true )]
	public partial interface IHtmlEmbed : IGlassBase 
	{
								/// <summary>
					/// The HtmlEmbedHtml field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: aecb3e6b-3dce-4e84-9bb2-b313b8bbcc20</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHtmlEmbedConstants.HtmlEmbedHtmlFieldName)]
					string HtmlEmbedHtml  {get; set;}
			
								/// <summary>
					/// The HtmlEmbedTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: af9e5a7a-0f51-4b33-a2ca-e83ddc75b442</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHtmlEmbedConstants.HtmlEmbedTitleFieldName)]
					string HtmlEmbedTitle  {get; set;}
			
				}


	public static partial class IHtmlEmbedConstants{

			public const string TemplateIdString = "e444df7d-4d75-4e48-857f-224d19766b4b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HtmlEmbed";

					
			public static readonly ID HtmlEmbedHtmlFieldId = new ID("aecb3e6b-3dce-4e84-9bb2-b313b8bbcc20");
			public const string HtmlEmbedHtmlFieldName = "HtmlEmbedHtml";
			
					
			public static readonly ID HtmlEmbedTitleFieldId = new ID("af9e5a7a-0f51-4b33-a2ca-e83ddc75b442");
			public const string HtmlEmbedTitleFieldName = "HtmlEmbedTitle";
			
			

	}

	
	/// <summary>
	/// HtmlEmbed
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/HtmlEmbed</para>	
	/// <para>ID: e444df7d-4d75-4e48-857f-224d19766b4b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHtmlEmbedConstants.TemplateIdString, Cachable = true)]
	public partial class HtmlEmbed  : GlassBase, IHtmlEmbed 
	{
	   
						/// <summary>
				/// The HtmlEmbedHtml field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: aecb3e6b-3dce-4e84-9bb2-b313b8bbcc20</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHtmlEmbedConstants.HtmlEmbedHtmlFieldName)]
				public virtual string HtmlEmbedHtml  {get; set;}
					
						/// <summary>
				/// The HtmlEmbedTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: af9e5a7a-0f51-4b33-a2ca-e83ddc75b442</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHtmlEmbedConstants.HtmlEmbedTitleFieldName)]
				public virtual string HtmlEmbedTitle  {get; set;}
					
			
	}
}













namespace Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Concrete
{


 	/// <summary>
	/// ISearch Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Search</para>	
	/// <para>ID: fc1fbaf6-d71c-4580-8f32-4f4ef3cd2094</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISearchConstants.TemplateIdString, Cachable = true )]
	public partial interface ISearch : IGlassBase , global::Glass.Mapper.Sc.Demo.Core.Models.sitecore.templates.Sugnl.Base.IPageBase
	{
								/// <summary>
					/// The SearchFor field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b6b68a26-c414-4f67-80d1-15e9edd21a15</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchForFieldName)]
					string SearchFor  {get; set;}
			
								/// <summary>
					/// The SearchNext field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 495480ac-47aa-40d2-a317-bb16f7ea2e23</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchNextFieldName)]
					string SearchNext  {get; set;}
			
								/// <summary>
					/// The SearchNoResults field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 4439277a-80a5-4199-8131-60f2b99f47c4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchNoResultsFieldName)]
					string SearchNoResults  {get; set;}
			
								/// <summary>
					/// The SearchPrevious field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 9c8a4438-ab8d-4cef-a597-96aa72eb9c01</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchPreviousFieldName)]
					string SearchPrevious  {get; set;}
			
								/// <summary>
					/// The SearchResultIcon field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 8eb29f83-f355-4684-a2dc-65eb15daa9f5</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchResultIconFieldName)]
					ExifImage SearchResultIcon  {get; set;}
			
								/// <summary>
					/// The SearchResultPerPage field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: 9c3b995e-3143-493b-bf8d-4751ab79c93e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchResultPerPageFieldName)]
					float SearchResultPerPage  {get; set;}
			
								/// <summary>
					/// The SearchSummary field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d44dd894-02f0-4689-8691-c25676f28833</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchSummaryFieldName)]
					string SearchSummary  {get; set;}
			
								/// <summary>
					/// The SearchWaterMark field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b1a76a98-25b3-41c8-b16b-96832bfb70ab</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISearchConstants.SearchWaterMarkFieldName)]
					string SearchWaterMark  {get; set;}
			
				}


	public static partial class ISearchConstants{

			public const string TemplateIdString = "fc1fbaf6-d71c-4580-8f32-4f4ef3cd2094";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Search";

					
			public static readonly ID SearchForFieldId = new ID("b6b68a26-c414-4f67-80d1-15e9edd21a15");
			public const string SearchForFieldName = "SearchFor";
			
					
			public static readonly ID SearchNextFieldId = new ID("495480ac-47aa-40d2-a317-bb16f7ea2e23");
			public const string SearchNextFieldName = "SearchNext";
			
					
			public static readonly ID SearchNoResultsFieldId = new ID("4439277a-80a5-4199-8131-60f2b99f47c4");
			public const string SearchNoResultsFieldName = "SearchNoResults";
			
					
			public static readonly ID SearchPreviousFieldId = new ID("9c8a4438-ab8d-4cef-a597-96aa72eb9c01");
			public const string SearchPreviousFieldName = "SearchPrevious";
			
					
			public static readonly ID SearchResultIconFieldId = new ID("8eb29f83-f355-4684-a2dc-65eb15daa9f5");
			public const string SearchResultIconFieldName = "SearchResultIcon";
			
					
			public static readonly ID SearchResultPerPageFieldId = new ID("9c3b995e-3143-493b-bf8d-4751ab79c93e");
			public const string SearchResultPerPageFieldName = "SearchResultPerPage";
			
					
			public static readonly ID SearchSummaryFieldId = new ID("d44dd894-02f0-4689-8691-c25676f28833");
			public const string SearchSummaryFieldName = "SearchSummary";
			
					
			public static readonly ID SearchWaterMarkFieldId = new ID("b1a76a98-25b3-41c8-b16b-96832bfb70ab");
			public const string SearchWaterMarkFieldName = "SearchWaterMark";
			
					
			public static readonly ID IPageTitlesLongTitleFieldId = new ID("73f291bc-4098-4702-b0da-8b0416751e81");
			public const string IPageTitlesLongTitleFieldName = "IPageTitlesLongTitle";
			
					
			public static readonly ID IPageTitlesShortTitleFieldId = new ID("04e95463-a928-4cc0-b855-fb9f341c2221");
			public const string IPageTitlesShortTitleFieldName = "IPageTitlesShortTitle";
			
					
			public static readonly ID IPageTitleSubTitleFieldId = new ID("adf2c63c-d097-4aec-b86f-571d772e441a");
			public const string IPageTitleSubTitleFieldName = "IPageTitleSubTitle";
			
			

	}

	
	/// <summary>
	/// Search
	/// <para></para>
	/// <para>Path: /sitecore/templates/Sugnl/Concrete/Search</para>	
	/// <para>ID: fc1fbaf6-d71c-4580-8f32-4f4ef3cd2094</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISearchConstants.TemplateIdString, Cachable = true)]
	public partial class Search  : GlassBase, ISearch 
	{
	   
						/// <summary>
				/// The SearchFor field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b6b68a26-c414-4f67-80d1-15e9edd21a15</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchForFieldName)]
				public virtual string SearchFor  {get; set;}
					
						/// <summary>
				/// The SearchNext field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 495480ac-47aa-40d2-a317-bb16f7ea2e23</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchNextFieldName)]
				public virtual string SearchNext  {get; set;}
					
						/// <summary>
				/// The SearchNoResults field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 4439277a-80a5-4199-8131-60f2b99f47c4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchNoResultsFieldName)]
				public virtual string SearchNoResults  {get; set;}
					
						/// <summary>
				/// The SearchPrevious field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 9c8a4438-ab8d-4cef-a597-96aa72eb9c01</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchPreviousFieldName)]
				public virtual string SearchPrevious  {get; set;}
					
						/// <summary>
				/// The SearchResultIcon field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8eb29f83-f355-4684-a2dc-65eb15daa9f5</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchResultIconFieldName)]
				public virtual ExifImage SearchResultIcon  {get; set;}
					
						/// <summary>
				/// The SearchResultPerPage field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: 9c3b995e-3143-493b-bf8d-4751ab79c93e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchResultPerPageFieldName)]
				public virtual float SearchResultPerPage  {get; set;}
					
						/// <summary>
				/// The SearchSummary field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d44dd894-02f0-4689-8691-c25676f28833</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchSummaryFieldName)]
				public virtual string SearchSummary  {get; set;}
					
						/// <summary>
				/// The SearchWaterMark field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b1a76a98-25b3-41c8-b16b-96832bfb70ab</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.SearchWaterMarkFieldName)]
				public virtual string SearchWaterMark  {get; set;}
					
						/// <summary>
				/// The IPageTitlesLongTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 73f291bc-4098-4702-b0da-8b0416751e81</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.IPageTitlesLongTitleFieldName)]
				public virtual string IPageTitlesLongTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitlesShortTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 04e95463-a928-4cc0-b855-fb9f341c2221</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.IPageTitlesShortTitleFieldName)]
				public virtual string IPageTitlesShortTitle  {get; set;}
					
						/// <summary>
				/// The IPageTitleSubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: adf2c63c-d097-4aec-b86f-571d772e441a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISearchConstants.IPageTitleSubTitleFieldName)]
				public virtual string IPageTitleSubTitle  {get; set;}
					
			
	}
}




